trigger:
  branches:
    include:
      - ni/current

pool:
  name: DevCentral-Docker

steps:
- task: Bash@3
  displayName: Generate version number
  inputs:
    targetType: 'inline'
    script: |
      TagNumber=$(git describe --abbrev=0 --tags)
      ShortHash=$(git rev-parse --short $(Build.SourceVersion))
      ImageVersion="$TagNumber-$ShortHash-ni"
      echo "##vso[task.setvariable variable=ImageVersion;]$ImageVersion"
      # ImageVersion will look like "8.3.6-8a2963c-ni"

- task: Docker@2
  displayName: Build docker image
  inputs:
    repository: '963234657927.dkr.ecr.us-east-1.amazonaws.com/ni-grafana'
    command: 'build'
    Dockerfile: 'Dockerfile'
    tags: |
      $(ImageVersion)
      latest

- task: Docker@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/ni/current'))
  displayName: Push docker image
  inputs:
    repository: "963234657927.dkr.ecr.us-east-1.amazonaws.com/ni-grafana"
    command: push
    Dockerfile: Dockerfile
    tags: |
      $(ImageVersion)
      latest

- task: Bash@3
  displayName: Docker cleanup
  inputs:
    targetType: 'inline'
    script: |
      docker system prune --volumes --force
