pool:
  name: DevCentral-Docker

trigger:
  - main
pr: none

steps:
- task: Bash@3
  displayName: Generate version number
  inputs:
    targetType: 'inline'
    script: |
      TagNumber=$(git describe --abbrev=0 --tags)
      ShortHash=$(git rev-parse --short $(Build.SourceVersion))
      ImageVersion="$TagNumber-$ShortHash-ni"
      echo "##vso[task.setvariable variable=ImageVersion;]$ImageVersion"
      # ImageVersion will look like "8.3.6-8a2963c-ni"

- task: Docker@2
  displayName: Build docker image
  inputs:
    repository: '963234657927.dkr.ecr.us-east-1.amazonaws.com/ni-grafana'
    command: 'build'
    Dockerfile: 'Dockerfile'
    tags: |
      $(ImageVersion)
      latest

- task: ECRPushImage@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  displayName: Push docker image with versioned tag
  inputs:
    awsCredentials: 'AWS SystemLink Cloud'
    regionName: 'us-east-1'
    imageSource: 'imagename'
    sourceImageName: '963234657927.dkr.ecr.us-east-1.amazonaws.com/ni-grafana'
    sourceImageTag: '$(ImageVersion)'
    repositoryName: 'ni-grafana'
    pushTag: '$(ImageVersion)'
    autoCreateRepository: true

# ECRPushImage does not support specifying multiple tags at push time. We therefore push a second time to
# additionally tag the image with the 'latest' tag. Note that this does not create a second image, and
# this push completes very quickly since it just adds an additional tag to the image.
- task: ECRPushImage@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  displayName: Tag image with latest
  inputs:
    awsCredentials: 'AWS SystemLink Cloud'
    regionName: 'us-east-1'
    imageSource: 'imagename'
    sourceImageName: '963234657927.dkr.ecr.us-east-1.amazonaws.com/ni-grafana'
    sourceImageTag: 'latest'
    repositoryName: 'ni-grafana'
    pushTag: 'latest'
    autoCreateRepository: true

- task: Bash@3
  displayName: Docker cleanup
  inputs:
    targetType: 'inline'
    script: |
      docker system prune --volumes --force