pool:
  name: DevCentral-Docker

variables:
  - group: 'niartifacts.jfrog.io'

trigger:
  - main
pr: none

stages:
  - stage: build_and_publish_ni_grafana_docker_image
    displayName: Build and Publish ni-grafana Docker Image
    jobs:
      - template: ../BuildTools/Pipeline/Templates/DockerBuildAndPublish.yml
        parameters:
          serviceName: ni-grafana
          dockerFilePath: Dockerfile
          dockerBuildContext: $(Build.Repository.LocalPath)
          dockerPreBuildSteps:
            - task: Bash@3
              displayName: Generate version number
              inputs:
                targetType: 'inline'
                script: |
                  TagNumber=$(git describe --abbrev=0 --tags)
                  ShortHash=$(git rev-parse --short $(Build.SourceVersion))
                  ImageVersion="$TagNumber-$ShortHash-ni"
                  echo "##vso[task.setvariable variable=ImageVersion;]$ImageVersion"
                  # ImageVersion will look like "8.3.6-8a2963c-ni"
          dockerImageTag: $(ImageVersion)