apiVersion: v2
name: nigrafana
description: A Helm chart that deploys Grafana and a Postgres database cluster for it

type: application
dependencies:
  - name: grafana
    version: ~6.20.6
    repository: "https://grafana.github.io/helm-charts"

version: 0.1.0
appVersion: "1.16.0"
